Parameters: 5333505
C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch_geometric\deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
Training steps: 60

  | Name  | Type       | Params | Mode
---------------------------------------------
0 | model | GNNEncoder | 5.3 M  | train
---------------------------------------------
5.3 M     Trainable params
0         Non-trainable params
5.3 M     Total params
21.334    Total estimated model params size (MB)
196       Modules in train mode
0         Modules in eval mode
Sanity Checking: |                                                                                                                 | 0/? [00:00<?, ?it/s]Validation dataset size: 64
Epoch 0: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.82it/s, v_num=t82f]
C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch_geometric\deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\loops\fit_loop.py:310: The number of training batches (3) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\autograd\graph.py:823: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [1, 256, 1, 1], strides() = [256, 1, 256, 256]
bucket_view.sizes() = [1, 256, 1, 1], strides() = [256, 1, 1, 1] (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\distributed\c10d\reducer.cpp:341.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Validation DataLoader 0:   0%|                                                                                                    | 0/64 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\COMP702\DIFUSCO-main\difusco\train.py", line 155, in <module>
    main(args)
  File "D:\COMP702\DIFUSCO-main\difusco\train.py", line 140, in main
    trainer.fit(model, ckpt_path=ckpt_path)
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 561, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\trainer\call.py", line 47, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\strategies\launchers\subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 599, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1012, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1056, in _run_stage
    self.fit_loop.run()
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 216, in run
    self.advance()
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 455, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\loops\training_epoch_loop.py", line 153, in run
    self.on_advance_end(data_fetcher)
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\loops\training_epoch_loop.py", line 394, in on_advance_end
    self.val_loop.run()
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\loops\utilities.py", line 179, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\loops\evaluation_loop.py", line 138, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
                                       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\loops\fetchers.py", line 134, in __next__
    batch = super().__next__()
            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\loops\fetchers.py", line 61, in __next__
    batch = next(self.iterator)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\utilities\combined_loader.py", line 341, in __next__
    out = next(self._iterator)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\utilities\combined_loader.py", line 142, in __next__
    out = next(self.iterators[0])
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\dataloader.py", line 708, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\dataloader.py", line 1455, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\dataloader.py", line 1505, in _process_data
    data.reraise()
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\_utils.py", line 733, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\_utils\worker.py", line 349, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 50, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\dataset.py", line 420, in __getitems__
    return [self.dataset[self.indices[idx]] for idx in indices]
            ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\COMP702\DIFUSCO-main\difusco\co_datasets\tsp_graph_dataset.py", line 41, in __getitem__
    points, tour = self.get_example(idx)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\COMP702\DIFUSCO-main\difusco\co_datasets\tsp_graph_dataset.py", line 24, in get_example
    line = self.file_lines[idx]
           ~~~~~~~~~~~~~~~^^^^^
IndexError: list index out of range

[rank0]: Traceback (most recent call last):
[rank0]:   File "D:\COMP702\DIFUSCO-main\difusco\train.py", line 155, in <module>
[rank0]:     main(args)
[rank0]:   File "D:\COMP702\DIFUSCO-main\difusco\train.py", line 140, in main
[rank0]:     trainer.fit(model, ckpt_path=ckpt_path)
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 561, in fit
[rank0]:     call._call_and_handle_interrupt(
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\trainer\call.py", line 47, in _call_and_handle_interrupt
[rank0]:     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\strategies\launchers\subprocess_script.py", line 105, in launch
[rank0]:     return function(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 599, in _fit_impl
[rank0]:     self._run(model, ckpt_path=ckpt_path)
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1012, in _run
[rank0]:     results = self._run_stage()
[rank0]:               ^^^^^^^^^^^^^^^^^
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1056, in _run_stage
[rank0]:     self.fit_loop.run()
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 216, in run
[rank0]:     self.advance()
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 455, in advance
[rank0]:     self.epoch_loop.run(self._data_fetcher)
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\loops\training_epoch_loop.py", line 153, in run
[rank0]:     self.on_advance_end(data_fetcher)
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\loops\training_epoch_loop.py", line 394, in on_advance_end
[rank0]:     self.val_loop.run()
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\loops\utilities.py", line 179, in _decorator
[rank0]:     return loop_run(self, *args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\loops\evaluation_loop.py", line 138, in run
[rank0]:     batch, batch_idx, dataloader_idx = next(data_fetcher)
[rank0]:                                        ^^^^^^^^^^^^^^^^^^
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\loops\fetchers.py", line 134, in __next__
[rank0]:     batch = super().__next__()
[rank0]:             ^^^^^^^^^^^^^^^^^^
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\loops\fetchers.py", line 61, in __next__
[rank0]:     batch = next(self.iterator)
[rank0]:             ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\utilities\combined_loader.py", line 341, in __next__
[rank0]:     out = next(self._iterator)
[rank0]:           ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorch_lightning\utilities\combined_loader.py", line 142, in __next__
[rank0]:     out = next(self.iterators[0])
[rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\dataloader.py", line 708, in __next__
[rank0]:     data = self._next_data()
[rank0]:            ^^^^^^^^^^^^^^^^^
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\dataloader.py", line 1455, in _next_data
[rank0]:     return self._process_data(data)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\dataloader.py", line 1505, in _process_data
[rank0]:     data.reraise()
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\_utils.py", line 733, in reraise
[rank0]:     raise exception
[rank0]: IndexError: Caught IndexError in DataLoader worker process 1.
[rank0]: Original Traceback (most recent call last):
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\_utils\worker.py", line 349, in _worker_loop
[rank0]:     data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 50, in fetch
[rank0]:     data = self.dataset.__getitems__(possibly_batched_index)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\dataset.py", line 420, in __getitems__
[rank0]:     return [self.dataset[self.indices[idx]] for idx in indices]
[rank0]:             ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
[rank0]:   File "D:\COMP702\DIFUSCO-main\difusco\co_datasets\tsp_graph_dataset.py", line 41, in __getitem__
[rank0]:     points, tour = self.get_example(idx)
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "D:\COMP702\DIFUSCO-main\difusco\co_datasets\tsp_graph_dataset.py", line 24, in get_example
[rank0]:     line = self.file_lines[idx]
[rank0]:            ~~~~~~~~~~~~~~~^^^^^
[rank0]: IndexError: list index out of range
