2025-08-28 16:01:53,783 INFO    MainThread:36664 [wandb_setup.py:_flush():80] Current SDK version is 0.21.1
2025-08-28 16:01:53,783 INFO    MainThread:36664 [wandb_setup.py:_flush():80] Configure stats pid to 36664
2025-08-28 16:01:53,783 INFO    MainThread:36664 [wandb_setup.py:_flush():80] Loading settings from C:\Users\faiso\.config\wandb\settings
2025-08-28 16:01:53,783 INFO    MainThread:36664 [wandb_setup.py:_flush():80] Loading settings from D:\COMP702\DIFUSCO-main\difusco\wandb\settings
2025-08-28 16:01:53,783 INFO    MainThread:36664 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-08-28 16:01:53,789 INFO    MainThread:36664 [wandb_init.py:setup_run_log_directory():703] Logging user logs to results\models\wandb\run-20250828_160153-arr4q8p9\logs\debug.log
2025-08-28 16:01:53,791 INFO    MainThread:36664 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to results\models\wandb\run-20250828_160153-arr4q8p9\logs\debug-internal.log
2025-08-28 16:01:53,791 INFO    MainThread:36664 [wandb_init.py:init():830] calling init triggers
2025-08-28 16:01:53,791 INFO    MainThread:36664 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-08-28 16:01:53,791 INFO    MainThread:36664 [wandb_init.py:init():871] starting backend
2025-08-28 16:01:54,059 INFO    MainThread:36664 [wandb_init.py:init():874] sending inform_init request
2025-08-28 16:01:54,127 INFO    MainThread:36664 [wandb_init.py:init():882] backend started and connected
2025-08-28 16:01:54,129 INFO    MainThread:36664 [wandb_init.py:init():953] updated telemetry
2025-08-28 16:01:54,131 INFO    MainThread:36664 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-08-28 16:01:54,955 INFO    MainThread:36664 [wandb_init.py:init():1029] starting run threads in backend
2025-08-28 16:01:55,461 INFO    MainThread:36664 [wandb_run.py:_console_start():2494] atexit reg
2025-08-28 16:01:55,461 INFO    MainThread:36664 [wandb_run.py:_redirect():2342] redirect: wrap_raw
2025-08-28 16:01:55,461 INFO    MainThread:36664 [wandb_run.py:_redirect():2411] Wrapping output streams.
2025-08-28 16:01:55,461 INFO    MainThread:36664 [wandb_run.py:_redirect():2434] Redirects installed.
2025-08-28 16:01:55,469 INFO    MainThread:36664 [wandb_init.py:init():1075] run started, returning control to user process
2025-08-28 16:10:05,098 WARNING MsgRouterThr:36664 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 200, in _read_packet_bytes
    data = self._sock.recv(self._bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 227, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 204, in _read_packet_bytes
    raise SockClientClosedError from e
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\router.py", line 56, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-08-28 16:10:05,111 INFO    MsgRouterThr:36664 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
