2025-08-06 15:56:20,920 INFO    MainThread:2836 [wandb_setup.py:_flush():80] Current SDK version is 0.21.0
2025-08-06 15:56:20,922 INFO    MainThread:2836 [wandb_setup.py:_flush():80] Configure stats pid to 2836
2025-08-06 15:56:20,922 INFO    MainThread:2836 [wandb_setup.py:_flush():80] Loading settings from C:\Users\faiso\.config\wandb\settings
2025-08-06 15:56:20,922 INFO    MainThread:2836 [wandb_setup.py:_flush():80] Loading settings from D:\COMP702\DIFUSCO-main\difusco\wandb\settings
2025-08-06 15:56:20,922 INFO    MainThread:2836 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-08-06 15:56:20,922 INFO    MainThread:2836 [wandb_init.py:setup_run_log_directory():703] Logging user logs to results\models\wandb\run-20250806_155620-np6yzzlr\logs\debug.log
2025-08-06 15:56:20,926 INFO    MainThread:2836 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to results\models\wandb\run-20250806_155620-np6yzzlr\logs\debug-internal.log
2025-08-06 15:56:20,926 INFO    MainThread:2836 [wandb_init.py:init():830] calling init triggers
2025-08-06 15:56:20,926 INFO    MainThread:2836 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-08-06 15:56:20,926 INFO    MainThread:2836 [wandb_init.py:init():871] starting backend
2025-08-06 15:56:21,630 INFO    MainThread:2836 [wandb_init.py:init():874] sending inform_init request
2025-08-06 15:56:21,780 INFO    MainThread:2836 [wandb_init.py:init():882] backend started and connected
2025-08-06 15:56:21,786 INFO    MainThread:2836 [wandb_init.py:init():953] updated telemetry
2025-08-06 15:56:21,788 INFO    MainThread:2836 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-08-06 15:56:22,650 INFO    MainThread:2836 [wandb_init.py:init():1029] starting run threads in backend
2025-08-06 15:56:30,116 INFO    MainThread:2836 [wandb_run.py:_console_start():2458] atexit reg
2025-08-06 15:56:30,117 INFO    MainThread:2836 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-08-06 15:56:30,117 INFO    MainThread:2836 [wandb_run.py:_redirect():2375] Wrapping output streams.
2025-08-06 15:56:30,117 INFO    MainThread:2836 [wandb_run.py:_redirect():2398] Redirects installed.
2025-08-06 15:56:30,120 INFO    MainThread:2836 [wandb_init.py:init():1075] run started, returning control to user process
2025-08-06 16:06:36,238 WARNING MsgRouterThr:2836 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 204, in _read_packet_bytes
    data = self._sock.recv(self._bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 231, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 208, in _read_packet_bytes
    raise SockClientClosedError from e
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\router.py", line 56, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\faiso\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-08-06 16:06:37,463 INFO    MsgRouterThr:2836 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
